"""add all domain models with service record review fields

Revision ID: a11e29de6dcd
Revises: fcf00b4539d0
Create Date: 2026-02-03 23:09:01.429786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11e29de6dcd'
down_revision: Union[str, None] = 'fcf00b4539d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='维度名称（如：颜色搭配）'),
    sa.Column('name_en', sa.String(length=50), nullable=True, comment='英文名称（如：color_matching）'),
    sa.Column('description', sa.Text(), nullable=True, comment='维度描述'),
    sa.Column('scoring_criteria', sa.Text(), nullable=True, comment='评分标准说明'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('is_active', sa.Integer(), nullable=True, comment='是否启用（1=是，0=否）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en')
    )
    op.create_index(op.f('ix_ability_dimensions_id'), 'ability_dimensions', ['id'], unique=False)
    op.create_index(op.f('ix_ability_dimensions_name'), 'ability_dimensions', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属美甲师ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='客户姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='电子邮件'),
    sa.Column('avatar_path', sa.String(length=500), nullable=True, comment='客户头像路径'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_active', sa.Integer(), nullable=True, comment='是否活跃（1=是，0=否）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_table('inspiration_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上传者ID'),
    sa.Column('image_path', sa.String(length=500), nullable=False, comment='图片存储路径'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='图片标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='图片描述'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表（颜色/风格/图案等，JSON数组）'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类（法式/渐变/贴片/彩绘等）'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='原始来源URL'),
    sa.Column('source_platform', sa.String(length=50), nullable=True, comment='来源平台（小红书/Instagram等）'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='被引用次数'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspiration_images_created_at'), 'inspiration_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspiration_images_id'), 'inspiration_images', ['id'], unique=False)
    op.create_index(op.f('ix_inspiration_images_user_id'), 'inspiration_images', ['user_id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('nail_shape', sa.String(length=50), nullable=True, comment='指甲形状（椭圆/方形/圆形/杏仁形等）'),
    sa.Column('nail_length', sa.String(length=50), nullable=True, comment='指甲长度（短/中/长）'),
    sa.Column('nail_condition', sa.Text(), nullable=True, comment='指甲状况描述（质地、健康状况等）'),
    sa.Column('nail_photos', sa.JSON(), nullable=True, comment='指甲照片路径列表（JSON数组）'),
    sa.Column('color_preferences', sa.JSON(), nullable=True, comment='喜欢的颜色列表（JSON数组）'),
    sa.Column('color_dislikes', sa.JSON(), nullable=True, comment='不喜欢的颜色列表（JSON数组）'),
    sa.Column('style_preferences', sa.JSON(), nullable=True, comment='喜欢的风格标签（简约/华丽/可爱/性感等，JSON数组）'),
    sa.Column('pattern_preferences', sa.Text(), nullable=True, comment='图案偏好描述'),
    sa.Column('allergies', sa.Text(), nullable=True, comment='过敏信息'),
    sa.Column('prohibitions', sa.Text(), nullable=True, comment='禁忌事项（不能接受的元素、颜色等）'),
    sa.Column('occasion_preferences', sa.JSON(), nullable=True, comment='场合偏好（日常/职场/派对/婚礼等，JSON对象）'),
    sa.Column('maintenance_preference', sa.String(length=50), nullable=True, comment='保养偏好（持久性/易维护/快速等）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_customer_id'), 'customer_profiles', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_table('design_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=False, comment='用于生成的AI提示词'),
    sa.Column('generated_image_path', sa.String(length=500), nullable=False, comment='生成的设计图路径'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='使用的AI模型版本（如 dall-e-3）'),
    sa.Column('design_target', sa.String(length=20), nullable=True, comment='设计目标（single/5nails/10nails）'),
    sa.Column('style_keywords', sa.JSON(), nullable=True, comment='风格关键词列表（JSON数组）'),
    sa.Column('reference_images', sa.JSON(), nullable=True, comment='参考图片路径列表（JSON数组）'),
    sa.Column('parent_design_id', sa.Integer(), nullable=True, comment='父设计方案ID（用于追踪迭代）'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('refinement_instruction', sa.Text(), nullable=True, comment='迭代优化指令'),
    sa.Column('estimated_duration', sa.Integer(), nullable=True, comment='预估耗时（分钟）'),
    sa.Column('estimated_materials', sa.JSON(), nullable=True, comment='预估材料清单（JSON数组）'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True, comment='难度等级（简单/中等/困难）'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='设计方案标题'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_archived', sa.Integer(), nullable=True, comment='是否归档（1=是，0=否）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['parent_design_id'], ['design_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_plans_created_at'), 'design_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_design_plans_customer_id'), 'design_plans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_design_plans_id'), 'design_plans', ['id'], unique=False)
    op.create_index(op.f('ix_design_plans_user_id'), 'design_plans', ['user_id'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('design_plan_id', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False, comment='服务日期'),
    sa.Column('service_duration', sa.Integer(), nullable=True, comment='服务时长（分钟）'),
    sa.Column('actual_image_path', sa.String(length=500), nullable=True, comment='实际完成图路径'),
    sa.Column('materials_used', sa.Text(), nullable=True, comment='实际使用的材料清单（自由文本）'),
    sa.Column('artist_review', sa.Text(), nullable=True, comment='美甲师复盘内容'),
    sa.Column('customer_feedback', sa.Text(), nullable=True, comment='客户反馈'),
    sa.Column('customer_satisfaction', sa.Integer(), nullable=True, comment='客户满意度评分（1-5星）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='其他备注'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/completed'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['design_plan_id'], ['design_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_created_at'), 'service_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_records_customer_id'), 'service_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_records_design_plan_id'), 'service_records', ['design_plan_id'], unique=False)
    op.create_index(op.f('ix_service_records_id'), 'service_records', ['id'], unique=False)
    op.create_index(op.f('ix_service_records_service_date'), 'service_records', ['service_date'], unique=False)
    op.create_index(op.f('ix_service_records_user_id'), 'service_records', ['user_id'], unique=False)
    op.create_table('ability_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, comment='评分（0-100）'),
    sa.Column('evidence', sa.Text(), nullable=True, comment='评分依据（AI 分析提取的证据）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['ability_dimensions.id'], ),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_records_created_at'), 'ability_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_ability_records_dimension_id'), 'ability_records', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_ability_records_id'), 'ability_records', ['id'], unique=False)
    op.create_index(op.f('ix_ability_records_service_record_id'), 'ability_records', ['service_record_id'], unique=False)
    op.create_index(op.f('ix_ability_records_user_id'), 'ability_records', ['user_id'], unique=False)
    op.create_table('comparison_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=False, comment='关联的服务记录ID'),
    sa.Column('similarity_score', sa.Integer(), nullable=False, comment='相似度评分（0-100）'),
    sa.Column('differences', sa.JSON(), nullable=True, comment='差异分析（JSON）'),
    sa.Column('suggestions', sa.JSON(), nullable=True, comment='改进建议（JSON数组）'),
    sa.Column('contextual_insights', sa.JSON(), nullable=True, comment='基于复盘和反馈的上下文洞察（JSON）'),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_results_analyzed_at'), 'comparison_results', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_comparison_results_id'), 'comparison_results', ['id'], unique=False)
    op.create_index(op.f('ix_comparison_results_service_record_id'), 'comparison_results', ['service_record_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparison_results_service_record_id'), table_name='comparison_results')
    op.drop_index(op.f('ix_comparison_results_id'), table_name='comparison_results')
    op.drop_index(op.f('ix_comparison_results_analyzed_at'), table_name='comparison_results')
    op.drop_table('comparison_results')
    op.drop_index(op.f('ix_ability_records_user_id'), table_name='ability_records')
    op.drop_index(op.f('ix_ability_records_service_record_id'), table_name='ability_records')
    op.drop_index(op.f('ix_ability_records_id'), table_name='ability_records')
    op.drop_index(op.f('ix_ability_records_dimension_id'), table_name='ability_records')
    op.drop_index(op.f('ix_ability_records_created_at'), table_name='ability_records')
    op.drop_table('ability_records')
    op.drop_index(op.f('ix_service_records_user_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_service_date'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_design_plan_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_customer_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_created_at'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_design_plans_user_id'), table_name='design_plans')
    op.drop_index(op.f('ix_design_plans_id'), table_name='design_plans')
    op.drop_index(op.f('ix_design_plans_customer_id'), table_name='design_plans')
    op.drop_index(op.f('ix_design_plans_created_at'), table_name='design_plans')
    op.drop_table('design_plans')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_customer_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_inspiration_images_user_id'), table_name='inspiration_images')
    op.drop_index(op.f('ix_inspiration_images_id'), table_name='inspiration_images')
    op.drop_index(op.f('ix_inspiration_images_created_at'), table_name='inspiration_images')
    op.drop_table('inspiration_images')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ability_dimensions_name'), table_name='ability_dimensions')
    op.drop_index(op.f('ix_ability_dimensions_id'), table_name='ability_dimensions')
    op.drop_table('ability_dimensions')
    # ### end Alembic commands ###
